### ISSUE TITLE
Week-07-navigation-highlight

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/navigation-highlight#1]
Need help with the code: 
1) Nav hover and highlighting the page using class="current"
2) Visual Difference
@thomasjbradley

**Comment by thomasjbradley** [comment]
1. The `:hover` should attached to the `a` tags not to the `li` tags:
https://github.com/VanshitaGandhi/navigation-highlight/blob/gh-pages/css/main.css#L70

2. Let’s start with the `font-size` first:
https://github.com/VanshitaGandhi/navigation-highlight/blob/gh-pages/css/main.css#L6
*Never* set the documents default size to anything smaller than `100%`

**Comment by thomasjbradley** [comment]
I see you have the CSS for current:
https://github.com/VanshitaGandhi/navigation-highlight/blob/gh-pages/css/main.css#L96

There are 2 problems:
1. There is no class `.nav` in the HTML, there is only the `<nav>` tag
2. The class of `.current` isn’t used anywhere in the HTML: it needs to be added to an `<a>` tag inside the navigation.

**Comment by VanshitaGandhi** [comment]
When I attach :hover to the a tag instead of li tag, it causes a visual difference

<img width="1341" alt="Screenshot 2019-10-24 at 11 51 21 AM" src="https://user-images.githubusercontent.com/55109487/67505366-1799fa00-f659-11e9-8f95-16c974537e08.png">

<img width="1341" alt="Screenshot 2019-10-24 at 11 51 37 AM" src="https://user-images.githubusercontent.com/55109487/67505369-18cb2700-f659-11e9-929b-a4c8edabf497.png">

@thomasjbradley

**Comment by VanshitaGandhi** [comment]
Can't figure how to bring all li tags in the same line because the browser shows them in the same line but markbot view varies.

<img width="399" alt="Screenshot 2019-10-24 at 12 26 43 PM" src="https://user-images.githubusercontent.com/55109487/67505686-b7f01e80-f659-11e9-95ea-b410a7d55244.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
*Re: hover on a—*

Yes, because many of the properties from the `<li>` need to move onto the `<a>`—in fact I think the only thin you need on the `<li>` is `display: inline-block`

**Comment by thomasjbradley** [comment]
*Re: navigation on one line—*

Use the Dev Tools & inspect the `<ul>` element. Does it have some browser default CSS that’s taking up extra space?

**Comment by VanshitaGandhi** [comment]
How can we align the text inside the li? I tried
```css
.nav li {
  display: inline-block;
  text-align: center;
}
```
@thomasjbradley

**Comment by thomasjbradley** [comment]
`text-align: center` works on children elements. So if you want to center the `<li>` tags, move it to the parent element.
